import "./globals.css";

// local font importu
import LocalFont from "next/font/local";

// remote font importu
import { Bitcount_Prop_Single } from "next/font/google";
import Header from "@/components/header";

// remote font kurulumu
const bitcount = Bitcount_Prop_Single({
  subsets: ["latin"],
  variable: "--font-bitcount",
});

// local font kurulumu
const moghul = LocalFont({
  src: "../assets/Moghul.ttf",
  variable: "--font-moghul",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex flex-col ${bitcount.variable} ${moghul.variable}`}
      >
        {/* <Header /> */}
        <main className="flex-1 text-3xl p-10 text-center my-5">
          {children}
        </main>
      </body>
    </html>
  );
}
