import "./globals.css";
// font importu
import { Bitcount_Prop_Single } from "next/font/google";

// font kurulumu
const bitcount = Bitcount_Prop_Single({
  subsets: ["latin"],
  variable: "--font-bit",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={bitcount.style} className={`antialiased`}>
        <main className="text-3xl p-10 text-center my-60">{children}</main>
      </body>
    </html>
  );
}
